export type GalleryCategory =
  | 'faith-discipleship'
  | 'books-study'
  | 'classroom-desks'
  | 'school-uniforms'
  | 'nutrition-community'
  | 'sanitation-repairs';

export interface GalleryCategoryMeta {
  id: GalleryCategory;
  label: string;
  description: string;
}

export const GALLERY_CATEGORIES: GalleryCategoryMeta[] = [
  {
    id: 'faith-discipleship',
    label: 'Faith & Discipleship',
    description: 'Christian fellowship, Sunday school, prayer circles, and discipleship gatherings.',
  },
  {
    id: 'books-study',
    label: 'Books & Learning',
    description: 'Course textbooks, notebooks, literacy materials, and student study supplies.',
  },
  {
    id: 'classroom-desks',
    label: 'Classrooms & Campus',
    description: 'Classroom buildings, wooden study desks, campus grounds, and learning spaces.',
  },
  {
    id: 'school-uniforms',
    label: 'Uniforms & Students',
    description: 'School uniforms, sweaters, footwear, student dignity, and campus life.',
  },
  {
    id: 'nutrition-community',
    label: 'Nutrition & Community Relief',
    description: 'Food care packages, dry grain supplies, community pantry support, and relief.',
  },
  {
    id: 'sanitation-repairs',
    label: 'Sanitation & Facility Repairs',
    description: 'Ventilated washrooms, plumbing installations, clean facilities, and repairs.',
  },
];

export type GalleryLayout = 'standard' | 'wide' | 'portrait';

export interface GalleryItem {
  id: string;
  type: 'photo' | 'video';
  title: string;
  subtitle?: string;
  category: GalleryCategory;
  categoryLabel: string;
  src: string;
  poster?: string;
  location?: string;
  duration?: string;
  objectPosition?: string;
  layout?: GalleryLayout;
  isFeatured?: boolean;
}

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'photo-discipleship-church',
    type: 'photo',
    title: 'Learning and Discipleship in Kibera',
    subtitle: 'Founder Maggie Mburu and community educators mentor young students inside a Kibera sanctuary, where classroom lessons and Christian discipleship meet under one roof.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/discipleship-kibera-church.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-field-outreach-13',
    type: 'photo',
    title: 'Assessing Grassroots Classroom Needs',
    subtitle: 'Maggie Mburu visits a community partner school in Kenya to assess student desk shortages and structural repairs firsthand, ensuring donor gifts meet urgent classroom needs.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-outreach-13.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-outreach-14',
    type: 'photo',
    title: 'Community Fellowship at Kibera Church',
    subtitle: 'Founder Maggie Mburu gathers with local pastors, teachers, and students inside the New CEA Pentecost Church in Kibera for a shared time of encouragement, mentorship, and prayer.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/field-outreach-14.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-field-outreach-18',
    type: 'photo',
    title: 'Hands-On Leadership in the Classroom',
    subtitle: 'Maggie Mburu spends time inside a partner classroom in Kenya, affirming the dedication of community teachers and encouraging students as they work through their daily math lessons.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-outreach-18.jpg',
    location: 'Kenya',
    objectPosition: 'object-top',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-community-fellowship',
    type: 'photo',
    title: 'Steps Toward a Brighter Future',
    subtitle: 'Students gather alongside mentors between classroom buildings in Kibera, exemplifying the community-driven care that keeps children engaged and motivated in school.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/DSCF0856.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-students-holding-books',
    type: 'photo',
    title: 'Empowered Through New Textbooks',
    subtitle: 'Students proudly show their new curriculum textbooks, celebrating the joy and dignity that come with having essential learning materials in their own hands.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/education-books-students.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-study-books-desks',
    type: 'photo',
    title: 'Fueling Community Nutrition',
    subtitle: 'A community kitchen stove prepared for lunchtime meal service, representing the foundational nutrition required to keep vulnerable children healthy and attentive in class.',
    category: 'nutrition-community',
    categoryLabel: 'Nutrition & Community Relief',
    src: '/images/DSCF0024.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-learning-1',
    type: 'photo',
    title: 'Building Security and Facility Upgrades',
    subtitle: 'Completed window grilles and door reinforcements provide a safe, secure environment for children to learn and store their classroom materials.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/field-learning-1.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-learning-supplies-delivery',
    type: 'photo',
    title: 'Equipped for the School Day',
    subtitle: 'Students stand proud in their matching school uniforms with backpacks ready, eager for another full day of learning and growth.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/volunteer-helping-with-donation-box1.jpeg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-amani-classroom-desks',
    type: 'photo',
    title: 'Reaching Every Neighborhood',
    subtitle: "Navigating the pathways of local informal settlements where Furaha's community workers walk each week to visit families and ensure children stay enrolled in school.",
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/DSCF0007.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-purity-teacher',
    type: 'photo',
    title: 'Tailoring Dignity and Opportunity',
    subtitle: 'A local tailor carefully measures a student for her custom school uniform, ensuring a perfect fit and clearing the way for her school year.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/Purity.jpg',
    location: 'Kenya',
    objectPosition: 'object-top',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-field-classroom-4',
    type: 'photo',
    title: 'Confidence in Every Step',
    subtitle: 'Two young scholars proudly pose in their new school sweaters and ties, embodying the confidence that quality school wear brings to every child.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/field-classroom-4.jpg',
    location: 'Kenya',
    objectPosition: 'object-top',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-field-campus-7',
    type: 'photo',
    title: 'Equipped for Academic Excellence',
    subtitle: 'Students gather in the courtyard with their core subject textbooks, ready to study together and prepare for national examinations.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/field-campus-7.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-westhill-uniforms',
    type: 'photo',
    title: 'Interactive Classroom Learning',
    subtitle: 'Founder Maggie Mburu and local teachers guide an animated lesson, creating an encouraging and lively learning environment for early-grade students.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/DSCF0817.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-uniform-wardrobe',
    type: 'photo',
    title: 'Standing Tall in School Uniforms',
    subtitle: 'Primary school students proudly wear their matching uniforms, fostering a shared sense of belonging, unity, and academic focus.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/uniform.jpeg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-students-10',
    type: 'photo',
    title: 'Joyful Community Fellowship',
    subtitle: "Founder Maggie Mburu shares a warm, loving embrace with a community member in Kenya, celebrating the genuine personal relationships and Christ-centered hope that define Furaha's work.",
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/field-students-10.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-portrait-12',
    type: 'photo',
    title: 'Ready for Tomorrow',
    subtitle: 'A young student stands with his new agriculture textbook, eager to learn practical skills that will serve his family and future.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/field-portrait-12.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-field-activity-3',
    type: 'photo',
    title: 'Restoring Community Kitchens',
    subtitle: 'Before-and-after structural renovations show the transition from deteriorated iron sheets to a sturdy, well-ventilated timber kitchen built for safe daily meal preparation.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/field-activity-3.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-maggie-founder',
    type: 'photo',
    title: 'Maggie Mburu, Founder of Furaha Ministries',
    subtitle: 'Guided by faith and a deep calling to love and serve vulnerable children across Kenya through education, daily nutrition, caring mentorship, and spiritual discipleship.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/maggienew2.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-nutrition-food-support',
    type: 'photo',
    title: 'Nourishing Body and Spirit',
    subtitle: 'Children gather in the shade for a warm, balanced plate of rice and stew, ensuring they have the energy and health to thrive both inside and outside the classroom.',
    category: 'nutrition-community',
    categoryLabel: 'Nutrition & Community Relief',
    src: '/images/Nutrition.png',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-field-community-5',
    type: 'photo',
    title: 'Celebrating New School Uniforms',
    subtitle: 'Founder Maggie Mburu celebrates with young students receiving their school uniforms, celebrating their dignity and the open door to continue their education.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/field-community-5.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-outreach-15',
    type: 'photo',
    title: 'Documenting Urgent School Needs',
    subtitle: 'Founder Maggie Mburu surveys and photographs classroom conditions firsthand in Kenya, ensuring donor partners see the direct, transparent reality of where their support goes.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-outreach-15.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-foodbank-volunteers',
    type: 'photo',
    title: 'Back-to-School Readiness',
    subtitle: 'Freshly pressed school uniforms, sturdy shoes, and exercise books organized and ready for distribution at the start of the academic term.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/group-people-volunteering-foodbank-poor-people.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-clothes-supplies-sorting',
    type: 'photo',
    title: 'Opening Doors with Textbooks',
    subtitle: 'A teacher and young scholars showcase newly arrived course textbooks, bringing curriculum resources directly into the hands of eager readers.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/volunteer-selecting-organizing-clothes-donations-charity.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-new-washrooms-completed',
    type: 'photo',
    title: 'Dignity and Educational Readiness',
    subtitle: 'Students stand proudly in their matching green uniforms, showing the confidence and self-respect that comes with having the required attire for school.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/video_frame_new_bathrooms.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-sanitation-construction',
    type: 'photo',
    title: 'United in Joy',
    subtitle: 'Young learners gather in a sunlit corridor, sharing smiles and camaraderie as they take their next steps together in school.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/video_frame_construction.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'standard',
    isFeatured: false,
  },
];

export const FEATURED_GALLERY_ITEMS: GalleryItem[] = GALLERY_ITEMS.filter((item) => item.isFeatured);
