export type GalleryCategory =
  | 'faith-discipleship'
  | 'books-study'
  | 'classroom-desks'
  | 'school-uniforms'
  | 'nutrition-community'
  | 'sanitation-repairs';

export interface GalleryCategoryMeta {
  id: GalleryCategory;
  label: string;
  description: string;
}

export const GALLERY_CATEGORIES: GalleryCategoryMeta[] = [
  {
    id: 'faith-discipleship',
    label: 'Faith & Discipleship',
    description: 'Fellowship, Sunday school, prayer, and discipleship gatherings.',
  },
  {
    id: 'books-study',
    label: 'Books & Learning',
    description: 'Course textbooks, notebooks, literacy materials, and study supplies.',
  },
  {
    id: 'classroom-desks',
    label: 'Classrooms & Campus',
    description: 'Classrooms, study desks, school grounds, and learning spaces.',
  },
  {
    id: 'school-uniforms',
    label: 'Uniforms & Students',
    description: 'School uniforms, sweaters, footwear, and student campus life.',
  },
  {
    id: 'nutrition-community',
    label: 'Nutrition & Community Relief',
    description: 'School meals, staple grain distributions, and food pantry support.',
  },
  {
    id: 'sanitation-repairs',
    label: 'Sanitation & Facility Repairs',
    description: 'Ventilated washrooms, plumbing, and structural facility repairs.',
  },
];

export type GalleryLayout = 'standard' | 'wide' | 'portrait';

export interface GalleryItem {
  id: string;
  type: 'photo' | 'video';
  title: string;
  subtitle?: string;
  category: GalleryCategory;
  categoryLabel: string;
  src: string;
  poster?: string;
  location?: string;
  duration?: string;
  objectPosition?: string;
  layout?: GalleryLayout;
  isFeatured?: boolean;
}

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'video-community-washroom-renovation',
    type: 'video',
    title: 'Community Washroom Renovation & Transformation',
    subtitle: 'Field video footage documenting the transformation from makeshift pit latrines to clean, ceramic-tiled ventilated washrooms.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/videos/community-washroom-transformation.mp4',
    poster: '/images/video_frame_new_bathrooms.jpg',
    location: 'Kenya',
    duration: '0:27',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-discipleship-church',
    type: 'photo',
    title: 'Learning and Discipleship in Kibera',
    subtitle: 'Maggie Mburu joins students and teachers inside a church in Kibera during a learning and discipleship session.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/discipleship-kibera-church.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-field-outreach-13',
    type: 'photo',
    title: 'Classroom Visit in Kenya',
    subtitle: 'Maggie Mburu visits a community school classroom to review student desks and facility conditions.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-outreach-13.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-outreach-14',
    type: 'photo',
    title: 'Fellowship at Kibera Church',
    subtitle: 'Maggie Mburu gathers with pastors, educators, and youth inside the New CEA Pentecost Church in Kibera for prayer and encouragement.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/field-outreach-14.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-field-outreach-18',
    type: 'photo',
    title: 'Classroom Time with Students',
    subtitle: 'Maggie Mburu alongside local teachers during a morning math lesson at a partner primary school.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-outreach-18.jpg',
    location: 'Kenya',
    objectPosition: 'object-top',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-community-fellowship',
    type: 'photo',
    title: 'Students and Mentors in Kibera',
    subtitle: 'Students and local mentors outside classroom buildings between study sessions.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/DSCF0856.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-students-holding-books',
    type: 'photo',
    title: 'New Curriculum Textbooks',
    subtitle: 'Students receive course textbooks and learning guides for the school term.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/education-books-students.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-study-books-desks',
    type: 'photo',
    title: 'Preparing the Daily Meal',
    subtitle: 'A community kitchen stove prepared for the daily school lunch program.',
    category: 'nutrition-community',
    categoryLabel: 'Nutrition & Community Relief',
    src: '/images/DSCF0024.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-learning-1',
    type: 'photo',
    title: 'Facility Repairs and Reinforcements',
    subtitle: 'Installed window grilles and door reinforcements helping protect learning materials and student spaces.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/field-learning-1.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-learning-supplies-delivery',
    type: 'photo',
    title: 'Ready for the School Day',
    subtitle: 'Students in uniform with backpacks ready for class.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/volunteer-helping-with-donation-box1.jpeg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-amani-classroom-desks',
    type: 'photo',
    title: 'Community Walkway',
    subtitle: 'Pathways through informal settlements where Furaha team members visit families and check on school enrollment.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/DSCF0007.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-purity-teacher',
    type: 'photo',
    title: 'Fitting School Uniforms',
    subtitle: 'Measuring a student for tailored school wear ahead of the term.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/Purity.jpg',
    location: 'Kenya',
    objectPosition: 'object-top',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-field-classroom-4',
    type: 'photo',
    title: 'School Sweaters and Uniforms',
    subtitle: 'Two students in their school sweaters and ties at the campus courtyard.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/field-classroom-4.jpg',
    location: 'Kenya',
    objectPosition: 'object-top',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-field-campus-7',
    type: 'photo',
    title: 'Textbooks in the Courtyard',
    subtitle: 'Students gathering outside between classes with their course textbooks.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/field-campus-7.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-westhill-uniforms',
    type: 'photo',
    title: 'Classroom Lesson in Progress',
    subtitle: 'Maggie Mburu and teachers working with early-primary students during an interactive lesson.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/DSCF0817.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-uniform-wardrobe',
    type: 'photo',
    title: 'Primary School Students in Uniform',
    subtitle: 'Primary school students in their matching uniforms during morning assembly.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/uniform.jpeg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-students-10',
    type: 'photo',
    title: 'Meeting Families and Partners',
    subtitle: 'Maggie Mburu greeting a community partner during a field visit in Kenya.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/field-students-10.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-portrait-12',
    type: 'photo',
    title: 'Practical Agriculture Textbook',
    subtitle: 'A student holding his agriculture textbook outside the classroom.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/field-portrait-12.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-field-activity-3',
    type: 'photo',
    title: 'Community Kitchen Repair',
    subtitle: 'Before-and-after work on the community kitchen: replacing damaged iron sheets with a ventilated timber structure.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/field-activity-3.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-maggie-founder',
    type: 'photo',
    title: 'Maggie Mburu, Founder',
    subtitle: 'Leading Furaha Ministries to support vulnerable children and youth in Kenya through education, daily meals, and mentorship.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/maggienew2.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-nutrition-food-support',
    type: 'photo',
    title: 'Daily Lunch for Students',
    subtitle: 'Children seated together for a warm meal of rice and stew provided during the school day.',
    category: 'nutrition-community',
    categoryLabel: 'Nutrition & Community Relief',
    src: '/images/Nutrition.png',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-field-community-5',
    type: 'photo',
    title: 'Distributing School Uniforms',
    subtitle: 'Maggie Mburu with young students receiving their uniforms before the school term begins.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/field-community-5.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-outreach-15',
    type: 'photo',
    title: 'Reviewing Classroom Facilities',
    subtitle: 'Maggie Mburu checking conditions and desk availability inside a community classroom.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-outreach-15.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-foodbank-volunteers',
    type: 'photo',
    title: 'School Supplies and Uniform Packs',
    subtitle: 'Uniforms, shoes, and exercise books organized for term distribution.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/group-people-volunteering-foodbank-poor-people.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-clothes-supplies-sorting',
    type: 'photo',
    title: 'Textbook Delivery',
    subtitle: 'Distributing newly arrived textbooks to teachers and students at the school.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/volunteer-selecting-organizing-clothes-donations-charity.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-new-washrooms-completed',
    type: 'photo',
    title: 'Completed Sanitation Facility',
    subtitle: 'The finished ventilated washroom block built to replace damaged facilities at the school.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/video_frame_new_bathrooms.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-sanitation-construction',
    type: 'photo',
    title: 'Facility Construction in Progress',
    subtitle: 'Carpentry and framing underway during on-site facility repairs in Kenya.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/video_frame_construction.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-settlement-walkway-path',
    type: 'photo',
    title: 'Community Pathways in Kibera',
    subtitle: 'Weathered alleyways connecting homes, schools, and community centers across informal settlements.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/DSCF0009.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-education-foundations',
    type: 'photo',
    title: 'Foundations of Education',
    subtitle: 'Providing primary school children with fundamental textbooks, stationery, and learning materials.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/Education.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-campus-courtyard',
    type: 'photo',
    title: 'Campus Gathering and Assembly',
    subtitle: 'Students assembled in the school courtyard between morning classes and outdoor study sessions.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-campus-8.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-students-displaying-textbooks',
    type: 'photo',
    title: 'Students Displaying Course Books',
    subtitle: 'School children proudly displaying their newly received curriculum textbooks in the school courtyard.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/field-campus-9.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-field-community-relief',
    type: 'photo',
    title: 'Community Outreach and Support',
    subtitle: 'Connecting directly with families and caregivers to assess emergency nutritional and schooling needs.',
    category: 'nutrition-community',
    categoryLabel: 'Nutrition & Community Relief',
    src: '/images/field-community-6.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-learning-chalkboard',
    type: 'photo',
    title: 'Dedicated Classroom Instruction',
    subtitle: 'Interactive teaching and chalkboard lessons providing personalized academic support to young learners.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-learning-2.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-field-outreach-youth',
    type: 'photo',
    title: 'Mentorship and Youth Encouragement',
    subtitle: 'Maggie Mburu and community partners encouraging secondary school students during weekend youth mentorship.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/field-outreach-16.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-outreach-leadership',
    type: 'photo',
    title: 'Community Leadership and Fellowship',
    subtitle: 'Partnering with local pastors, elders, and educators to coordinate community safety and educational support.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/field-outreach-17.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-students-dignity',
    type: 'photo',
    title: 'Dignity Through School Uniforms',
    subtitle: 'Students standing tall in clean, well-fitted uniforms that foster belonging and academic focus.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/field-students-11.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-washroom-carpentry-framing',
    type: 'photo',
    title: 'Carpentry for Washroom Upgrades',
    subtitle: 'Local craftsmen constructing durable timber door frames and supports for student washroom blocks.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/video_frame_carpentry.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-sanitation-timber-materials',
    type: 'photo',
    title: 'Building Supplies On Site',
    subtitle: 'High-grade timber posts, framing materials, and galvanized iron sheets delivered for facility construction.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/video_frame_materials.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-deteriorated-latrines-before',
    type: 'photo',
    title: 'Sanitation Needs Before Intervention',
    subtitle: 'The fragile, unventilated pit latrines that posed health and safety risks before Furaha rebuilt them.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/video_frame_need.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-old-bathrooms-structure',
    type: 'photo',
    title: 'Original Facility Structure',
    subtitle: 'Documenting dilapidated structural conditions prior to full sanitation refurbishment.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/video_frame_old_bathrooms.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-school-facility-transformation',
    type: 'photo',
    title: 'Campus Transformation Overview',
    subtitle: 'Comprehensive documentation showing classrooms, sanitation blocks, and student learning environments.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/video_master_poster.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-dispatch-evening',
    type: 'photo',
    title: 'Field Update: Student Engagement',
    subtitle: 'On-the-ground photo from our local field team documenting daily student outreach in the community.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/WhatsApp Image 2026-09-03 at 10.53.23 PM3.jpeg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-dispatch-community',
    type: 'photo',
    title: 'Field Update: Community Care',
    subtitle: 'Direct dispatch from Kenya showing community elders and mentors working alongside Furaha coordinators.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/WhatsApp Image 2026-09-03 at 11.10.21 PM.jpeg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
];

export const FEATURED_GALLERY_ITEMS: GalleryItem[] = GALLERY_ITEMS.filter((item) => item.isFeatured);

export const FEATURED_VIDEO_ITEM: GalleryItem =
  GALLERY_ITEMS.find((item) => item.id === 'video-community-washroom-renovation') ||
  GALLERY_ITEMS.find((item) => item.type === 'video') ||
  GALLERY_ITEMS[0];

export interface CauseInfo {
  label: string;
  shortLabel: string;
  cause: string;
  impactNote: string;
}

export const getCauseForCategory = (category: string): CauseInfo => {
  switch (category) {
    case 'sanitation-repairs':
      return {
        label: 'Support Facility Upgrades',
        shortLabel: 'Support Repairs',
        cause: 'Sanitation & Facility Repairs',
        impactNote: '100% goes directly into on-the-ground materials and construction in Kenya.',
      };
    case 'classroom-desks':
      return {
        label: 'Support Classroom Desks',
        shortLabel: 'Support Desks',
        cause: 'Classroom Desks & Spaces',
        impactNote: '100% goes directly into student desks, boards, and classroom repairs.',
      };
    case 'school-uniforms':
      return {
        label: 'Fund School Uniforms',
        shortLabel: 'Fund Uniforms',
        cause: 'School Uniforms & Supplies',
        impactNote: '100% goes directly into tailored uniforms, sweaters, and shoes.',
      };
    case 'books-study':
      return {
        label: 'Provide Study Books',
        shortLabel: 'Provide Books',
        cause: 'Books & Learning Supplies',
        impactNote: '100% goes directly into textbooks, workbooks, and curriculum sets.',
      };
    case 'nutrition-community':
      return {
        label: 'Provide Student Meals',
        shortLabel: 'Provide Meals',
        cause: 'Nutrition & Daily Meals',
        impactNote: '100% goes directly into daily lunches, grains, and kitchen supplies.',
      };
    case 'faith-discipleship':
      return {
        label: 'Support Youth Mentorship',
        shortLabel: 'Support Mentors',
        cause: 'Faith & Community Mentorship',
        impactNote: '100% goes directly into community outreach, Bibles, and youth mentorship.',
      };
    default:
      return {
        label: 'Support This Program',
        shortLabel: 'Support',
        cause: 'Where Needed Most',
        impactNote: '100% goes directly into on-the-ground programs in Kenya.',
      };
  }
};

