export type GalleryCategory =
  | 'faith-discipleship'
  | 'books-study'
  | 'classroom-desks'
  | 'school-uniforms'
  | 'nutrition-community'
  | 'sanitation-repairs';

export interface GalleryCategoryMeta {
  id: GalleryCategory;
  label: string;
  description: string;
}

export const GALLERY_CATEGORIES: GalleryCategoryMeta[] = [
  {
    id: 'faith-discipleship',
    label: 'Faith & Discipleship',
    description: 'Fellowship, Sunday school, prayer, and discipleship gatherings.',
  },
  {
    id: 'books-study',
    label: 'Books & Learning',
    description: 'Course textbooks, notebooks, literacy materials, and study supplies.',
  },
  {
    id: 'classroom-desks',
    label: 'Classrooms & Campus',
    description: 'Classrooms, study desks, school grounds, and learning spaces.',
  },
  {
    id: 'school-uniforms',
    label: 'Uniforms & Students',
    description: 'School uniforms, sweaters, footwear, and student campus life.',
  },
  {
    id: 'nutrition-community',
    label: 'Nutrition & Community Relief',
    description: 'School meals, staple grain distributions, and food pantry support.',
  },
  {
    id: 'sanitation-repairs',
    label: 'Sanitation & Facility Repairs',
    description: 'Ventilated washrooms, plumbing, and structural facility repairs.',
  },
];

export type GalleryLayout = 'standard' | 'wide' | 'portrait';

export interface GalleryItem {
  id: string;
  type: 'photo' | 'video';
  title: string;
  subtitle?: string;
  category: GalleryCategory;
  categoryLabel: string;
  src: string;
  poster?: string;
  location?: string;
  duration?: string;
  objectPosition?: string;
  layout?: GalleryLayout;
  isFeatured?: boolean;
}

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'photo-discipleship-church',
    type: 'photo',
    title: 'Learning and Discipleship in Kibera',
    subtitle: 'Maggie Mburu joins students and teachers inside a church in Kibera during a learning and discipleship session.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/discipleship-kibera-church.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-field-outreach-13',
    type: 'photo',
    title: 'Classroom Visit in Kenya',
    subtitle: 'Maggie Mburu visits a community school classroom to review student desks and facility conditions.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-outreach-13.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-outreach-14',
    type: 'photo',
    title: 'Fellowship at Kibera Church',
    subtitle: 'Maggie Mburu gathers with pastors, educators, and youth inside the New CEA Pentecost Church in Kibera for prayer and encouragement.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/field-outreach-14.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-field-outreach-18',
    type: 'photo',
    title: 'Classroom Time with Students',
    subtitle: 'Maggie Mburu alongside local teachers during a morning math lesson at a partner primary school.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-outreach-18.jpg',
    location: 'Kenya',
    objectPosition: 'object-top',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-community-fellowship',
    type: 'photo',
    title: 'Students and Mentors in Kibera',
    subtitle: 'Students and local mentors outside classroom buildings between study sessions.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/DSCF0856.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-students-holding-books',
    type: 'photo',
    title: 'New Curriculum Textbooks',
    subtitle: 'Students receive course textbooks and learning guides for the school term.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/education-books-students.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-study-books-desks',
    type: 'photo',
    title: 'Preparing the Daily Meal',
    subtitle: 'A community kitchen stove prepared for the daily school lunch program.',
    category: 'nutrition-community',
    categoryLabel: 'Nutrition & Community Relief',
    src: '/images/DSCF0024.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-learning-1',
    type: 'photo',
    title: 'Facility Repairs and Reinforcements',
    subtitle: 'Installed window grilles and door reinforcements helping protect learning materials and student spaces.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/field-learning-1.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-learning-supplies-delivery',
    type: 'photo',
    title: 'Ready for the School Day',
    subtitle: 'Students in uniform with backpacks ready for class.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/volunteer-helping-with-donation-box1.jpeg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-amani-classroom-desks',
    type: 'photo',
    title: 'Community Walkway',
    subtitle: 'Pathways through informal settlements where Furaha team members visit families and check on school enrollment.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/DSCF0007.jpg',
    location: 'Kibera, Nairobi, Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-purity-teacher',
    type: 'photo',
    title: 'Fitting School Uniforms',
    subtitle: 'Measuring a student for tailored school wear ahead of the term.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/Purity.jpg',
    location: 'Kenya',
    objectPosition: 'object-top',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-field-classroom-4',
    type: 'photo',
    title: 'School Sweaters and Uniforms',
    subtitle: 'Two students in their school sweaters and ties at the campus courtyard.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/field-classroom-4.jpg',
    location: 'Kenya',
    objectPosition: 'object-top',
    layout: 'standard',
    isFeatured: false,
  },
  {
    id: 'photo-field-campus-7',
    type: 'photo',
    title: 'Textbooks in the Courtyard',
    subtitle: 'Students gathering outside between classes with their course textbooks.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/field-campus-7.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-westhill-uniforms',
    type: 'photo',
    title: 'Classroom Lesson in Progress',
    subtitle: 'Maggie Mburu and teachers working with early-primary students during an interactive lesson.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/DSCF0817.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-uniform-wardrobe',
    type: 'photo',
    title: 'Primary School Students in Uniform',
    subtitle: 'Primary school students in their matching uniforms during morning assembly.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/uniform.jpeg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-students-10',
    type: 'photo',
    title: 'Meeting Families and Partners',
    subtitle: 'Maggie Mburu greeting a community partner during a field visit in Kenya.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/field-students-10.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-portrait-12',
    type: 'photo',
    title: 'Practical Agriculture Textbook',
    subtitle: 'A student holding his agriculture textbook outside the classroom.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/field-portrait-12.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-field-activity-3',
    type: 'photo',
    title: 'Community Kitchen Repair',
    subtitle: 'Before-and-after work on the community kitchen: replacing damaged iron sheets with a ventilated timber structure.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/field-activity-3.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-maggie-founder',
    type: 'photo',
    title: 'Maggie Mburu, Founder',
    subtitle: 'Leading Furaha Ministries to support vulnerable children and youth in Kenya through education, daily meals, and mentorship.',
    category: 'faith-discipleship',
    categoryLabel: 'Faith & Discipleship',
    src: '/images/maggienew2.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-nutrition-food-support',
    type: 'photo',
    title: 'Daily Lunch for Students',
    subtitle: 'Children seated together for a warm meal of rice and stew provided during the school day.',
    category: 'nutrition-community',
    categoryLabel: 'Nutrition & Community Relief',
    src: '/images/Nutrition.png',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: true,
  },
  {
    id: 'photo-field-community-5',
    type: 'photo',
    title: 'Distributing School Uniforms',
    subtitle: 'Maggie Mburu with young students receiving their uniforms before the school term begins.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/field-community-5.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-field-outreach-15',
    type: 'photo',
    title: 'Reviewing Classroom Facilities',
    subtitle: 'Maggie Mburu checking conditions and desk availability inside a community classroom.',
    category: 'classroom-desks',
    categoryLabel: 'Classrooms & Campus',
    src: '/images/field-outreach-15.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-foodbank-volunteers',
    type: 'photo',
    title: 'School Supplies and Uniform Packs',
    subtitle: 'Uniforms, shoes, and exercise books organized for term distribution.',
    category: 'school-uniforms',
    categoryLabel: 'Uniforms & Students',
    src: '/images/group-people-volunteering-foodbank-poor-people.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'portrait',
    isFeatured: false,
  },
  {
    id: 'photo-clothes-supplies-sorting',
    type: 'photo',
    title: 'Textbook Delivery',
    subtitle: 'Distributing newly arrived textbooks to teachers and students at the school.',
    category: 'books-study',
    categoryLabel: 'Books & Learning',
    src: '/images/volunteer-selecting-organizing-clothes-donations-charity.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-new-washrooms-completed',
    type: 'photo',
    title: 'Completed Sanitation Facility',
    subtitle: 'The finished ventilated washroom block built to replace damaged facilities at the school.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/video_frame_new_bathrooms.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'wide',
    isFeatured: false,
  },
  {
    id: 'photo-sanitation-construction',
    type: 'photo',
    title: 'Facility Construction in Progress',
    subtitle: 'Carpentry and framing underway during on-site facility repairs in Kenya.',
    category: 'sanitation-repairs',
    categoryLabel: 'Sanitation & Facility Repairs',
    src: '/images/video_frame_construction.jpg',
    location: 'Kenya',
    objectPosition: 'object-center',
    layout: 'standard',
    isFeatured: false,
  },
];

export const FEATURED_GALLERY_ITEMS: GalleryItem[] = GALLERY_ITEMS.filter((item) => item.isFeatured);
